# Generated by Django 3.0.5 on 2020-05-03 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="deck",
            field=models.ManyToManyField(to="cards.Deck"),
        ),
    ]
